from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text()
    if old not in text:
        raise SystemExit(f"anchor missing in {path}")
    file.write_text(text.replace(old, new, 1))


extension = "apps/extension/src/storage/profile-sync.ts"
replace_once(
    extension,
    '''function reconcileFacts(\n  baseFacts: ProfileFact[],\n  localFacts: ProfileFact[],\n  remoteFacts: ProfileFact[],\n): ProfileFact[] {\n  const baseByKey = new Map(baseFacts.map((fact) => [fact.key, fact] as const));\n  const localByKey = new Map(\n    localFacts.map((fact) => [fact.key, fact] as const),\n  );\n  const remoteByKey = new Map(\n    remoteFacts.map((fact) => [fact.key, fact] as const),\n  );\n  const protectedKeys = new Set(\n    [...localFacts, ...remoteFacts]\n      .filter((fact) => fact.protected)\n      .map((fact) => fact.key),\n  );\n  const selectedProtected = new Map<string, ProfileFact>();\n\n  for (const key of protectedKeys) {\n    const selected = chooseProtectedFact(\n      baseByKey.get(key),\n      localByKey.get(key),\n      remoteByKey.get(key),\n    );\n    if (selected) selectedProtected.set(key, selected);\n  }\n\n  const facts = baseFacts.map(\n    (fact) => selectedProtected.get(fact.key) ?? fact,\n  );\n  const seen = new Set(facts.map((fact) => fact.key));\n  for (const key of [...selectedProtected.keys()].sort()) {\n    if (!seen.has(key)) facts.push(selectedProtected.get(key)!);\n  }\n  return facts;\n}\n''',
    '''function reconcileFacts(\n  baseFacts: ProfileFact[],\n  localFacts: ProfileFact[],\n  remoteFacts: ProfileFact[],\n): ProfileFact[] {\n  const baseByKey = new Map(baseFacts.map((fact) => [fact.key, fact] as const));\n  const localByKey = new Map(\n    localFacts.map((fact) => [fact.key, fact] as const),\n  );\n  const remoteByKey = new Map(\n    remoteFacts.map((fact) => [fact.key, fact] as const),\n  );\n  const allKeys = new Set(\n    [...baseFacts, ...localFacts, ...remoteFacts].map((fact) => fact.key),\n  );\n  const selected = new Map<string, ProfileFact>();\n\n  for (const key of allKeys) {\n    const baseFact = baseByKey.get(key);\n    const localFact = localByKey.get(key);\n    const remoteFact = remoteByKey.get(key);\n    const protectedFact = Boolean(\n      baseFact?.protected || localFact?.protected || remoteFact?.protected,\n    );\n    const choice = protectedFact\n      ? chooseProtectedFact(baseFact, localFact, remoteFact)\n      : (laterFact(localFact, remoteFact) ?? baseFact);\n    if (choice) selected.set(key, choice);\n  }\n\n  const facts = baseFacts.map((fact) => selected.get(fact.key) ?? fact);\n  const seen = new Set(facts.map((fact) => fact.key));\n  for (const key of [...selected.keys()].sort()) {\n    if (!seen.has(key)) facts.push(selected.get(key)!);\n  }\n  return facts;\n}\n''',
)

owner = "apps/owner-workspace/app/vault-client.ts"
replace_once(
    owner,
    '''function reconcileFacts(\n  baseFacts: ProfileFact[],\n  localFacts: ProfileFact[],\n  remoteFacts: ProfileFact[],\n): ProfileFact[] {\n  const baseByKey = new Map(baseFacts.map((fact) => [fact.key, fact]));\n  const localByKey = new Map(localFacts.map((fact) => [fact.key, fact]));\n  const remoteByKey = new Map(remoteFacts.map((fact) => [fact.key, fact]));\n  const keys = new Set(\n    [...localFacts, ...remoteFacts]\n      .filter((fact) => fact.protected)\n      .map((fact) => fact.key),\n  );\n  const selected = new Map<string, ProfileFact>();\n  for (const key of keys) {\n    const baseFact = baseByKey.get(key);\n    const localFact = localByKey.get(key);\n    const remoteFact = remoteByKey.get(key);\n    if (\n      localFact &&\n      remoteFact &&\n      factFingerprint(localFact.value) === factFingerprint(remoteFact.value)\n    ) {\n      selected.set(\n        key,\n        (confirmedProtected(baseFact)\n          ? baseFact\n          : confirmedProtected(localFact)\n            ? localFact\n            : confirmedProtected(remoteFact)\n              ? remoteFact\n              : (baseFact ?? laterFact(localFact, remoteFact)))!,\n      );\n    } else {\n      const choice = confirmedProtected(localFact)\n        ? localFact\n        : confirmedProtected(remoteFact)\n          ? remoteFact\n          : (baseFact ?? laterFact(localFact, remoteFact));\n      if (choice) selected.set(key, choice);\n    }\n  }\n  const result = baseFacts.map((fact) => selected.get(fact.key) ?? fact);\n  const seen = new Set(result.map((fact) => fact.key));\n  for (const key of [...selected.keys()].sort()) {\n    if (!seen.has(key)) result.push(selected.get(key)!);\n  }\n  return result;\n}\n''',
    '''function reconcileFacts(\n  baseFacts: ProfileFact[],\n  localFacts: ProfileFact[],\n  remoteFacts: ProfileFact[],\n): ProfileFact[] {\n  const baseByKey = new Map(baseFacts.map((fact) => [fact.key, fact]));\n  const localByKey = new Map(localFacts.map((fact) => [fact.key, fact]));\n  const remoteByKey = new Map(remoteFacts.map((fact) => [fact.key, fact]));\n  const keys = new Set(\n    [...baseFacts, ...localFacts, ...remoteFacts].map((fact) => fact.key),\n  );\n  const selected = new Map<string, ProfileFact>();\n  for (const key of keys) {\n    const baseFact = baseByKey.get(key);\n    const localFact = localByKey.get(key);\n    const remoteFact = remoteByKey.get(key);\n    const protectedFact = Boolean(\n      baseFact?.protected || localFact?.protected || remoteFact?.protected,\n    );\n    if (!protectedFact) {\n      const choice = laterFact(localFact, remoteFact) ?? baseFact;\n      if (choice) selected.set(key, choice);\n      continue;\n    }\n    if (\n      localFact &&\n      remoteFact &&\n      factFingerprint(localFact.value) === factFingerprint(remoteFact.value)\n    ) {\n      selected.set(\n        key,\n        (confirmedProtected(baseFact)\n          ? baseFact\n          : confirmedProtected(localFact)\n            ? localFact\n            : confirmedProtected(remoteFact)\n              ? remoteFact\n              : (baseFact ?? laterFact(localFact, remoteFact)))!,\n      );\n    } else {\n      const choice = confirmedProtected(localFact)\n        ? localFact\n        : confirmedProtected(remoteFact)\n          ? remoteFact\n          : (baseFact ?? laterFact(localFact, remoteFact));\n      if (choice) selected.set(key, choice);\n    }\n  }\n  const result = baseFacts.map((fact) => selected.get(fact.key) ?? fact);\n  const seen = new Set(result.map((fact) => fact.key));\n  for (const key of [...selected.keys()].sort()) {\n    if (!seen.has(key)) result.push(selected.get(key)!);\n  }\n  return result;\n}\n''',
)

# Extension regression: sparse newer remote cannot erase an unrelated ordinary fact.
ext_test = Path("apps/extension/src/storage/profile-sync.test.ts")
text = ext_test.read_text()
insert = '''\n  it("preserves unrelated ordinary facts when a newer profile is sparse", () => {\n    const local = profile(\n      [\n        fact("email", "aadil@example.test", { protected: false }),\n        fact("preferred_name", "Aadil", { protected: false }),\n      ],\n      "2026-08-14T12:00:00.000Z",\n    );\n    const remote = profile(\n      [\n        fact("preferred_name", "Aadil M", {\n          protected: false,\n          updatedAt: "2026-08-14T12:05:00.000Z",\n        }),\n      ],\n      "2026-08-14T12:05:00.000Z",\n    );\n\n    const reconciled = reconcileProtectedProfile(local, remote);\n    expect(\n      reconciled.facts.find((candidate) => candidate.key === "email")?.value,\n    ).toBe("aadil@example.test");\n    expect(\n      reconciled.facts.find((candidate) => candidate.key === "preferred_name")\n        ?.value,\n    ).toBe("Aadil M");\n  });\n'''
closing = "\n});\n"
if not text.endswith(closing):
    raise SystemExit("extension profile sync test closing anchor missing")
ext_test.write_text(text[:-len(closing)] + insert + closing)

# Owner regression mirrors the exact sparse cross-device case.
owner_test = Path("apps/owner-workspace/tests/profile-vault.test.mjs")
text = owner_test.read_text()
text += '''\n\ntest("sparse newer profile cannot erase unrelated ordinary facts", () => {\n  const local = snapshot({\n    facts: [\n      fact({\n        factId: "email",\n        key: "email",\n        value: "aadil@example.test",\n        category: "CONTACT",\n        protected: false,\n      }),\n      fact({\n        factId: "preferred-old",\n        key: "preferred_name",\n        value: "Aadil",\n        protected: false,\n      }),\n    ],\n    updatedAt: "2026-08-14T18:00:00.000Z",\n  });\n  const remote = snapshot({\n    facts: [\n      fact({\n        factId: "preferred-new",\n        key: "preferred_name",\n        value: "Aadil M",\n        protected: false,\n        updatedAt: "2026-08-14T18:05:00.000Z",\n      }),\n    ],\n    updatedAt: "2026-08-14T18:05:00.000Z",\n  });\n\n  const reconciled = reconcileProfileSnapshots(local, remote);\n  assert.equal(\n    reconciled.facts.find((candidate) => candidate.key === "email")?.value,\n    "aadil@example.test",\n  );\n  assert.equal(\n    reconciled.facts.find((candidate) => candidate.key === "preferred_name")\n      ?.value,\n    "Aadil M",\n  );\n});\n'''
owner_test.write_text(text)
